name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Instalar dependências
        run: go mod tidy
        working-directory: ./backend-golang

      - name: Rodar testes
        run: go test ./...
        working-directory: ./backend-golang

      - name: Build
        run: go build -v ./cmd/server
        working-directory: ./backend-golang 