version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - node:20-slim
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SERVER_URL=${SERVER_URL}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    restart: always
    volumes:
      - next-cache:/app/.next/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  next-cache:
    driver: local
    